language: node_js
node_js:
  - "node"
script:
  - npm run coverage | npx coveralls
  - npm run build

deploy:
  provider: pages
  local_dir: './dist'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master