language: node_js
node_js:
  - "node"
script:
  - npm test
  - npm run build
jobs:
  include:
    - stage: Produce coverage
      node_js: node
      script: npm run coverage | npx coveralls
deploy:
  provider: pages
  local_dir: './dist'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master